myset=({"apple", "banana", "cherry"})
myset.add("orange")
print(myset)
newSet= {"kiwi", "mango", "banana"}
print(type(newSet))
myset.update(newSet)
print(myset)
myset.remove("mango")
print(myset)
myset.discard("pumpkin")
print(myset)
myset.pop()
print(myset)
myset.clear()
print(myset)